export const FETCH_POKEMON_LIST = 'FETCH_POKEMONS_LIST';

export const FETCH_POKEMON_LIST_NEXT = 'FETCH_POKEMONS_NEXT_PAGE';

export const FETCH_POKEMON_DATA = 'FETCH_POKEMONS_DATA';

export const UPDATE_POKEMON_SHALLOW_DATA = 'UPDATE_POKEMON_SHALLOW_DATA';

export const UPDATE_POKEMON_DEEP_DATA = 'UPDATE_POKEMON_DEEP_DATA';

export const NETWORK_FAIL = 'SOMETHING_GONE_WRONG';
