export const THEME = {
  default: { badge: 'red', bg: 'yellow' },
  bug: { badge: '#8CB330', bg: 'red' },
  dark: { badge: '#58575F', bg: 'red' },
  dragon: { badge: '#0F6AC0', bg: 'red' },
  electric: { badge: '#EED535', bg: 'red' },
  fairy: { badge: '#ED6EC7', bg: 'red' },
  fighting: { badge: '#D04164', bg: 'red' },
  fire: { badge: '#FD7D24', bg: '#FFA756' },
  flying: { badge: '#748FC9', bg: 'red' },
  ghost: { badge: '#556AAE', bg: 'red' },
  grass: { badge: '#62B957', bg: '#8BBE8A' },
  ground: { badge: '#DD7748', bg: 'red' },
  ice: { badge: '#61CEC0', bg: 'red' },
  normal: { badge: '#9DA0AA', bg: 'red' },
  poison: { badge: '#A552CC', bg: 'red' },
  psychic: { badge: '#EA5D60', bg: 'red' },
  rock: { badge: '#BAAB82', bg: 'red' },
  steel: { badge: '#417D9A', bg: 'red' },
  water: { badge: '#4A90DA', bg: 'red' },
};
